// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of adding files/folders to a layer.
 */
export type AddFilesReport = {
  /**
   * Basenames of items added to the layer directory.
   */
  added: Array<string>;
};
