// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkshopFileKind } from "./WorkshopFileKind";

/**
 * A single file entry in a layer's content directory.
 */
export type ContentEntry = {
  /**
   * Path relative to the layer root, always POSIX-style (`/`).
   */
  relativePath: string;
  sizeBytes: bigint;
  kind: WorkshopFileKind;
};
