// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerContent } from "./LayerContent";

/**
 * A project's content directory as a flat per-layer listing.
 */
export type ContentTree = { layers: Array<LayerContent> };
