// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditModMetadataArgs = {
  displayName: string | null;
  tags: Array<string> | null;
  champions: Array<string> | null;
  maps: Array<string> | null;
  setThumbnailPath: string | null;
  removeThumbnail: boolean | null;
};
