// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentEntry } from "./ContentEntry";

/**
 * The files inside a single layer directory.
 */
export type LayerContent = {
  name: string;
  fileCount: number;
  totalSizeBytes: bigint;
  entries: Array<ContentEntry>;
};
