// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of a diagnostic check result.
 *
 * Variants are declared best-to-worst (`Ok < Info < Warn < Bad`). The
 * frontend re-sorts to display worst-first; do not derive `Ord` from this
 * declaration order without revisiting the UI sort logic in
 * `DiagnosticsReport.tsx`.
 */
export type Severity = "ok" | "info" | "warn" | "bad";
