// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Domain errors specific to workshop operations.
 *
 * Sent over IPC as the `context` payload of an `AppError` with code `WORKSHOP`.
 * Frontend code can switch on `kind` to handle each variant.
 */
export type WorkshopError = { kind: "LAYER_FILE_CONFLICT"; conflicts: Array<string> };
