// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirror of [`ltk_file::LeagueFileKind`] with `ts-rs` bindings. Kept in sync
 * manually — the upstream enum is small and stable, and mirroring lets us
 * export a TypeScript union without fighting external crate attributes.
 */
export type WorkshopFileKind =
  | "animation"
  | "jpeg"
  | "light_grid"
  | "lua_obj"
  | "map_geometry"
  | "png"
  | "tga"
  | "preload"
  | "property_bin"
  | "property_bin_override"
  | "riot_string_table"
  | "simple_skin"
  | "skeleton"
  | "static_mesh_ascii"
  | "static_mesh_binary"
  | "svg"
  | "texture"
  | "texture_dds"
  | "unknown"
  | "world_geometry"
  | "wwise_bank"
  | "wwise_package";
